### ISSUE TITLE
Track.js

### ISSUE THREAD

**Issue by farishkash** [Aaron-Day/Jammming#2]
https://github.com/Aaron-Day/Jammming/blob/343e638d099fff9d6b45aceb3aa91b495ab6d856/src/Components/Track/Track.js#L32

You are calling the renderAction link and trying to generate a link instead of another link.  Which is going to break some things  since you can't have a link as an descendant of another one in react.  The other issue here is you aren't calling this function properly, you are missing the () which is stopping this app completely.  This is mention in the dev tools that there is an issue with the Track.js file.

```
 </div>
        {this.renderAction()}
      </div>
```

**Comment by Aaron-Day** [comment]
Did not know about this, thanks. Added
