### ISSUE TITLE
Term has never been added to the state.

### ISSUE THREAD

**Issue by farishkash** [Aaron-Day/Jammming#3]
https://github.com/Aaron-Day/Jammming/blob/343e638d099fff9d6b45aceb3aa91b495ab6d856/src/Components/SearchBar/SearchBar.js#L12

Nowhere is term added to the state, so when you try to setState to an object properly that doesn't exist, nothing happens.

You can add it to this component by just declaring it in the constructor area.

```
this.state = {
      term: ''
    };

```

**Comment by Aaron-Day** [comment]
Added
