### ISSUE TITLE
Double return

### ISSUE THREAD

**Issue by farishkash** [Aaron-Day/Jammming#6]
https://github.com/Aaron-Day/Jammming/blob/343e638d099fff9d6b45aceb3aa91b495ab6d856/src/util/Spotify.js#L34-L42

map already returns a new array as part of the iterator, syntax below should be enough.

return jsonResponse.tracks.items.map(track => ({ 
     id: track.id, 
     name: track.name, 
     artist: track.artists[0].name, 
     album: track.album.name, 
     uri: track.uri 
 })

**Comment by Aaron-Day** [comment]
Corrected
